# Generated by Django 4.2.24 on 2026-05-09 03:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_bought",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="retail_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="wholesale_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="repair",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="repairitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("قطع غيار", "قطع غيار"),
                    ("زيوت", "زيوت"),
                    ("خدمات", "خدمات / أجور يد"),
                    ("أخرى", "أخرى"),
                ],
                default="قطع غيار",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="repairitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="repairitem",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="salary",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="workersalary",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
