# Generated by Django 4.2.24 on 2026-05-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_product_price_alter_product_price_bought_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(("price__gte", 0)),
                name="product_price_non_negative",
                violation_error_message="السعر لا يمكن أن يكون سالبًا",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(("price_bought__gte", 0)),
                name="product_price_bought_non_negative",
                violation_error_message="سعر الشراء لا يمكن أن يكون سالبًا",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(("wholesale_price__gte", 0)),
                name="product_wholesale_price_non_negative",
                violation_error_message="سعر الجملة لا يمكن أن يكون سالبًا",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(("retail_price__gte", 0)),
                name="product_retail_price_non_negative",
                violation_error_message="سعر القطاعي لا يمكن أن يكون سالبًا",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gte", 0)),
                name="product_quantity_non_negative",
                violation_error_message="الكمية لا يمكن أن تكون سالبة",
            ),
        ),
        migrations.AddConstraint(
            model_name="repair",
            constraint=models.CheckConstraint(
                check=models.Q(("total_cost__gte", 0)),
                name="repair_total_cost_non_negative",
                violation_error_message="إجمالي التكلفة لا يمكن أن يكون سالبًا",
            ),
        ),
        migrations.AddConstraint(
            model_name="repair",
            constraint=models.CheckConstraint(
                check=models.Q(("mileage__gte", 0)),
                name="repair_mileage_non_negative",
                violation_error_message="العداد لا يمكن أن يكون سالبًا",
            ),
        ),
        migrations.AddConstraint(
            model_name="repairitem",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gte", 1)),
                name="repair_item_quantity_positive",
                violation_error_message="الكمية يجب أن تكون أكبر من الصفر",
            ),
        ),
        migrations.AddConstraint(
            model_name="repairitem",
            constraint=models.CheckConstraint(
                check=models.Q(("price__gte", 0)),
                name="repair_item_price_non_negative",
                violation_error_message="السعر لا يمكن أن يكون سالبًا",
            ),
        ),
        migrations.AddConstraint(
            model_name="repairitem",
            constraint=models.CheckConstraint(
                check=models.Q(("total__gte", 0)),
                name="repair_item_total_non_negative",
                violation_error_message="الإجمالي لا يمكن أن يكون سالبًا",
            ),
        ),
        migrations.AddConstraint(
            model_name="worker",
            constraint=models.CheckConstraint(
                check=models.Q(("salary__gte", 0)),
                name="salary_non_negative",
                violation_error_message="الراتب لا يمكن أن يكون سالبًا",
            ),
        ),
        migrations.AddConstraint(
            model_name="workersalary",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gte", 0)),
                name="worker_salary_amount_non_negative",
                violation_error_message="المبلغ لا يمكن أن يكون سالبًا",
            ),
        ),
    ]
