from django.urls import path

from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("customers/", views.customers, name="customers"),
    path("add_customer/", views.add_customer, name="add_customer"),
    path("edit_customer/<int:pk>/", views.edit_customer, name="edit_customer"),
    path("delete_customer/<int:pk>/", views.delete_customer, name="delete_customer"),
    path("customer_details/<int:pk>/", views.customer_details, name="customer_details"),
    path("cars/", views.cars, name="cars"),
    path("add_car/", views.add_car, name="add_car"),
    path("edit_car/<int:pk>/", views.edit_car, name="edit_car"),
    path("delete_car/<int:pk>/", views.delete_car, name="delete_car"),
    path("car_details/<int:pk>/", views.car_details, name="car_details"),
    path("repairs/", views.repairs, name="repairs"),
    path("add_repair/", views.add_repair, name="add_repair"),
    path("edit_repair/<int:pk>/", views.edit_repair, name="edit_repair"),
    path("delete_repair/<int:pk>/", views.delete_repair, name="delete_repair"),
    path("repair_details/<int:pk>/", views.repair_details, name="repair_details"),
    path("add_repair_item/<int:repair_pk>/", views.add_repair_item, name="add_repair_item"),
    path("edit_repair_item/<int:repair_pk>/<int:item_pk>/", views.edit_repair_item, name="edit_repair_item"),
    path("delete_repair_item/<int:pk>/", views.delete_repair_item, name="delete_repair_item"),
    path("invoices/", views.invoices, name="invoices"),
    path("invoice/<int:repair_pk>/", views.view_invoice, name="view_invoice"),
    path("add_invoice/", views.add_invoice, name="add_invoice"),
    path("products/", views.products, name="products"),
    path("add_product/", views.add_product, name="add_product"),
    path("edit_product/<int:pk>/", views.edit_product, name="edit_product"),
    path("delete_product/<int:pk>/", views.delete_product, name="delete_product"),
    path("product_details/<int:pk>/", views.product_details, name="product_details"),
    path("api/products/<str:product_type>/", views.get_products_by_type, name="api_products_by_type"),
    path("workers/", views.workers, name="workers"),
    path("add_worker/", views.add_worker, name="add_worker"),
    path("edit_worker/<int:pk>/", views.edit_worker, name="edit_worker"),
    path("delete_worker/<int:pk>/", views.delete_worker, name="delete_worker"),
    path("worker_details/<int:pk>/", views.worker_details, name="worker_details"),
    path("add_worker_salary/<int:worker_pk>/", views.add_worker_salary, name="add_worker_salary"),
    path("delete_worker_salary/<int:pk>/", views.delete_worker_salary, name="delete_worker_salary"),
    path("edit_worker_salary/<int:pk>/", views.edit_worker_salary, name="edit_worker_salary"),
    path("earnings/", views.earnings, name="earnings"),
    path("earnings/details/<str:category>/", views.earnings_details, name="earnings_details"),
    path("download_database/", views.download_database, name="download_database"),
    path("restore_database/", views.restore_database, name="restore_database"),
    path("search/", views.global_search, name="global_search"),
]
